[project]
name = "xfm-quote-finder"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.112",
  "uvicorn[standard]>=0.30",
  "spotipy>=2.23",
]

[tool.uv]
dev-dependencies = ["pytest>=8.2"]